[package]
name = "pub-sub-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "2.5.0"
futures-executor = "0.3.31"
futures-util = "0.3.31"
log = "0.4.22"
env_logger = "0.11.6"

